export const ActionTypes = {
  SET_CARDS: "SET_CARDS",
  SELECTED_PRODUCT: "SELECTED_PRODUCT",
  REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
  SET_CATEGORY_PRODUCTS:"SET_CATEGORY_PRODUCTS",
  ADD_ITEM:"ADD_ITEM",
  DELETE_ITEM:"DELETE_ITEM",
  SORT_PRODUCTS:"SORT_PRODUCTS"
};
